#══════════════════════════════════════════════════════════════════════════════
#  OK Inteligência Artificial
#  Formação ISP AI Starter - Provedores Inteligentes
#══════════════════════════════════════════════════════════════════════════════
#
#  Stack:       MinIO (Object Storage S3-Compatible)
#  Versão:      1.3.0
#
#  URLS:
#    - Console (Admin): https://cdn.${DOMAIN}/
#    - API S3:          https://s3.${DOMAIN}/
#
#  CREDENCIAIS:
#    - Usuário: admin
#    - Senha:   Admin@Starter2025
#
#  DEPENDÊNCIAS: traefik
#
#══════════════════════════════════════════════════════════════════════════════
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command: server /data --console-address ":9001"
    environment:
      - TZ=America/Sao_Paulo
      # Credenciais
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      # URLs
      - MINIO_BROWSER_REDIRECT_URL=https://cdn.${DOMAIN}
      - MINIO_SERVER_URL=https://s3.${DOMAIN}
    volumes:
      - /storage/minio/data:/data
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        # API S3 (porta 9000)
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.minio-s3.rule=Host(`s3.${DOMAIN}`)
        - traefik.http.routers.minio-s3.entrypoints=websecure
        - traefik.http.routers.minio-s3.tls.certresolver=letsencrypt
        - traefik.http.routers.minio-s3.service=minio-s3
        - traefik.http.services.minio-s3.loadbalancer.server.port=9000
        - traefik.http.services.minio-s3.loadbalancer.passHostHeader=true
        # Console Admin (porta 9001)
        - traefik.http.routers.minio-console.rule=Host(`cdn.${DOMAIN}`)
        - traefik.http.routers.minio-console.entrypoints=websecure
        - traefik.http.routers.minio-console.tls.certresolver=letsencrypt
        - traefik.http.routers.minio-console.service=minio-console
        - traefik.http.services.minio-console.loadbalancer.server.port=9001
        - traefik.http.services.minio-console.loadbalancer.passHostHeader=true
networks:
  network_public:
    external: true