#══════════════════════════════════════════════════════════════════════════════
#  OK Inteligência Artificial
#  Formação ISP AI Starter - Provedores Inteligentes
#══════════════════════════════════════════════════════════════════════════════
#
#  Stack:       OpenClaw (AI Personal Assistant)
#  Versão:      1.0.0
#
#  URL:
#    - Web UI: https://ai.${DOMAIN}/
#
#  CREDENCIAIS:
#    - Gateway Token: ${OPENCLAW_GATEWAY_TOKEN}
#    - Auth: ${OPENCLAW_AUTH_USER} / ${OPENCLAW_AUTH_PASSWORD}
#
#  DEPENDÊNCIAS: traefik
#
#══════════════════════════════════════════════════════════════════════════════
services:
  openclaw:
    image: alpine/openclaw:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    environment:
      - HOME=/home/node
      - TERM=xterm-256color
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      # Autenticação Gateway
      - OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
      # Autenticação Web UI (Basic Auth)
      - AUTH_USERNAME=${OPENCLAW_AUTH_USER}
      - AUTH_PASSWORD=${OPENCLAW_AUTH_PASSWORD}
      # Provedor de IA (configurar pelo menos um)
      - OPENAI_API_KEY=${OPENCLAW_OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${OPENCLAW_ANTHROPIC_API_KEY}
    command:
      - node
      - dist/index.js
      - gateway
      - --bind
      - lan
      - --port
      - "18789"
      - --allow-unconfigured
    ports:
      - "18789:18789"
    volumes:
      - /storage/openclaw/config:/home/node/.openclaw
      - /storage/openclaw/workspace:/home/node/.openclaw/workspace
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.openclaw.rule=Host(`ai.${DOMAIN}`)
        - traefik.http.routers.openclaw.entrypoints=websecure
        - traefik.http.routers.openclaw.tls.certresolver=letsencrypt
        - traefik.http.routers.openclaw.service=openclaw
        - traefik.http.services.openclaw.loadbalancer.server.port=18789
        - traefik.http.services.openclaw.loadbalancer.passhostheader=true
networks:
  network_public:
    external: true
