#══════════════════════════════════════════════════════════════════════════════
#  OK Inteligência Artificial
#  Formação ISP AI Starter - Provedores Inteligentes
#══════════════════════════════════════════════════════════════════════════════
#
#  Stack:       WordPress (Site Institucional)
#  Versão:      1.1.0
#
#  URL:
#    - WordPress: https://app.${DOMAIN}/
#
#  DEPENDÊNCIAS: mysql, traefik
#
#══════════════════════════════════════════════════════════════════════════════
services:
  wordpress:
    image: wordpress:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    volumes:
      - /storage/wordpress/data:/var/www/html
    networks:
      - network_public
    environment:
      # MySQL
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.swarm.network=network_public
        - traefik.http.routers.wordpress.rule=Host(`app.${DOMAIN}`)
        - traefik.http.routers.wordpress.entrypoints=websecure
        - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
        - traefik.http.routers.wordpress.service=wordpress
        - traefik.http.services.wordpress.loadbalancer.server.port=80
        - traefik.http.services.wordpress.loadbalancer.passhostheader=true
networks:
  network_public:
    external: true