#══════════════════════════════════════════════════════════════════════════════
#  OK Inteligência Artificial
#  Formação ISP AI Starter - Provedores Inteligentes
#══════════════════════════════════════════════════════════════════════════════
#
#  Stack:       N8N Webhook (Worker)
#  Versão:      1.5.0
#
#  DEPENDÊNCIAS: postgres, redis, traefik, n8n-editor
#
#══════════════════════════════════════════════════════════════════════════════
services:
  n8n-webhook:
    image: n8nio/n8n:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command: webhook
    environment:
      # Timezone
      - TZ=America/Sao_Paulo
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # URLs
      - N8N_HOST=wf.${DOMAIN}
      - N8N_EDITOR_BASE_URL=https://wf.${DOMAIN}/
      - WEBHOOK_URL=https://wb.${DOMAIN}/
      # Porta e Protocolo
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_ENDPOINT_WEBHOOK=webhook
      # Segurança (não alterar após primeira execução)
      - N8N_ENCRYPTION_KEY=94cda0b762a72d07f68564c8ba8fdc0e523b544e69fee154f64061ce6b34ab8c
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_ENV=production
      # Modo Queue (fila com Redis)
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      # Task Runners
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      # Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      # PostgreSQL
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Interface
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_WORKFLOW_TAGS_DISABLED=false
      - N8N_HIDE_USAGE_PAGE=false
      # Métricas e Diagnósticos
      - N8N_METRICS=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PAYLOAD_SIZE_MAX=16
      - N8N_LOG_LEVEL=info
      # Retenção de Execuções
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # Nodes e Extensões
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes
      # IA (configurar para habilitar)
      - N8N_AI_ENABLED=false
      - N8N_AI_PROVIDER=openai
      - N8N_AI_OPENAI_API_KEY=
      # SMTP (configurar antes de usar)
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.seudominio.com.br
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=username@seudominio.com.br
      - N8N_SMTP_PASS=${SMTP_PASSWORD}
      - N8N_SMTP_SENDER=seuemail@seudominio.com.br
      - N8N_SMTP_SSL=true
    volumes:
      - /storage/n8n/data:/home/node/.n8n
      - /storage/n8n/nodes:/data/nodes
    networks:
      - network_public
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 768M
        reservations:
          cpus: "0.25"
          memory: 384M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.n8n-webhook.rule=Host(`wb.${DOMAIN}`)
        - traefik.http.routers.n8n-webhook.entrypoints=websecure
        - traefik.http.routers.n8n-webhook.tls.certresolver=letsencrypt
        - traefik.http.services.n8n-webhook.loadbalancer.server.port=5678
        - traefik.http.services.n8n-webhook.loadbalancer.passHostHeader=true
networks:
  network_public:
    external: true